using PublishTool.Core.Models;

namespace PublishTool.Core.Services.BuildRunners;

/// <summary>
/// Finds the APK/AAB a Gradle build just produced. Searches for Gradle's conventional
/// <c>&lt;module&gt;/build/outputs/&lt;apk|bundle&gt;/&lt;variant&gt;/...</c> layout rather than
/// hardcoding a module name (usually "app", but not guaranteed) -- this project structure is
/// generated by Capacitor/Cordova, not chosen by whoever registers the project with PublishTool.
/// </summary>
internal static class AndroidArtifactLocator
{
    public static string Find(string searchRoot, string variant, AndroidArtifactType artifactType)
    {
        var kind = artifactType == AndroidArtifactType.Aab ? "bundle" : "apk";
        var extension = artifactType == AndroidArtifactType.Aab ? "*.aab" : "*.apk";

        if (Directory.Exists(searchRoot))
        {
            var outputsDirs = Directory.EnumerateDirectories(searchRoot, "outputs", SearchOption.AllDirectories)
                .Where(d => string.Equals(Path.GetFileName(Path.GetDirectoryName(d)), "build", StringComparison.OrdinalIgnoreCase));

            foreach (var outputsDir in outputsDirs)
            {
                var kindDir = Path.Combine(outputsDir, kind);
                if (!Directory.Exists(kindDir))
                {
                    continue;
                }

                var found = Directory.EnumerateFiles(kindDir, extension, SearchOption.AllDirectories)
                    .FirstOrDefault(f => Path.GetDirectoryName(f)!.Contains(variant, StringComparison.OrdinalIgnoreCase));
                if (found is not null)
                {
                    return found;
                }
            }
        }

        throw new InvalidOperationException(
            $"Couldn't find a built {extension} file for build variant '{variant}' under '{searchRoot}' -- " +
            "the build may have failed, or produced output somewhere this tool doesn't recognize.");
    }
}
